### ISSUE TITLE
Nice Work!

### ISSUE THREAD

**Issue by hoemotion** [Raphsonite/raphsonite.github.io#1]
One quick question: is there any way to print the output.png in the console **colored** i could only figure out how to print them in white (it would be pretty neat because we would be able to add something like a „banner“ to our python projects

**Comment by Raphsonite** [comment]
Hi! I dont think that is so easy! But should be possible. Perhaps this?
https://stackoverflow.com/questions/287871/how-to-print-colored-text-to-the-terminal


Op ma 10 jan. 2022 om 14:28 schreef karma.meme ***@***.***>:

**Comment by hoemotion** [comment]
seems like it‘s possible to print a color by having it‘s rgb value via \033[38;2;{r};{g};{b}m 
i will try using this for my project
thank you for your advice
